app = "starbound-server"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "starbound-saves"
  destination = "/opt/starbound/storage"

[[services]]
  protocol = "udp"
  internal_port = 21025
  [[services.ports]]
    port = 21025
    handlers = ["udp"]
